name: Validate ckans
on:
    push:
        branches:
            - master
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
jobs:
    Validate:
        runs-on: ubuntu-latest
        steps:
            - name: Get CKAN-meta repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Cache downloads
              if: ${{ github.event_name == 'pull_request' }}
              uses: actions/cache@v2
              with:
                  path: .cache
                  key: downloads-${{ github.run_id }}
                  restore-keys: |
                      downloads-
            - name: Test modified ckans
              uses: KSP-CKAN/xKAN-meta_testing@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
                  GITHUB_EVENT_BEFORE: ${{ github.event.before }}
              with:
                  source: commits
                  pull request body: ${{ github.event.pull_request.body }}
            - name: Chmod cached files so actions/cache can read them
              run: sudo chmod -R a+r .cache
